// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Conciergelink_coded_ui
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// StartCL - Use 'StartCLParams' to pass parameters into this method.
        /// </summary>
        public void StartCL()
        {

            // Launch '%ProgramFiles%\BuildingLink\ConciergeLink\ConciergeLink.exe'
            ApplicationUnderTest conciergeLinkApplication = ApplicationUnderTest.Launch(this.StartCLParams.ExePath, this.StartCLParams.AlternateExePath);
        }
        
        /// <summary>
        /// LoginToCL - Use 'LoginToCLParams' to pass parameters into this method.
        /// </summary>
        public void LoginToCL()
        {
            #region Variable Declarations
            WpfEdit uIItemEdit = this.UIConciergeLinkWindow.UIItemCustom.UIContentScrollViewerPane.UIUserNameText.UIItemEdit;
            WpfEdit uIItemEdit1 = this.UIConciergeLinkWindow.UIItemCustom.UIContentScrollViewerPane.UIPasswordText.UIItemEdit;
            WpfButton uILogInButton = this.UIConciergeLinkWindow.UIItemCustom.UIContentScrollViewerPane.UILogInButton;
            #endregion

            // Type 'itechdev' in first text box next to 'User Name' label
            uIItemEdit.Text = this.LoginToCLParams.UIItemEditText;

            // Click first text box next to 'Password' label
            Mouse.Click(uIItemEdit1, new Point(38, 31));

            // Type '********' in first text box next to 'Password' label
            Keyboard.SendKeys(uIItemEdit1, this.LoginToCLParams.UIItemEditSendKeys, true);

            // Click 'Log In' button
            Mouse.Click(uILogInButton, new Point(137, 32));
        }
        
        /// <summary>
        /// CloseCL
        /// </summary>
        public void CloseCL()
        {
            #region Variable Declarations
            WpfButton uIKButton = this.UIConciergeLinkWindow.UIItemCustom1.UIKButton;
            #endregion

            // Click 'K' button
            Mouse.Click(uIKButton, new Point(8, 13));
        }
        
        /// <summary>
        /// IsLoggedIn - Use 'IsLoggedInExpectedValues' to pass parameters into this method.
        /// </summary>
        public void IsLoggedIn()
        {
            #region Variable Declarations
            WpfComboBox uIItemComboBox = this.UIConciergeLinkWindow.UIItemCustom2.UIZButton.UIItemComboBox;
            #endregion

            // Verify that the 'ControlType' property of first combo box next to 'Z' button contains 'ComboBox'
            StringAssert.Contains(uIItemComboBox.ControlType.ToString(), this.IsLoggedInExpectedValues.UIItemComboBoxControlType);
        }
        
        #region Properties
        public virtual StartCLParams StartCLParams
        {
            get
            {
                if ((this.mStartCLParams == null))
                {
                    this.mStartCLParams = new StartCLParams();
                }
                return this.mStartCLParams;
            }
        }
        
        public virtual LoginToCLParams LoginToCLParams
        {
            get
            {
                if ((this.mLoginToCLParams == null))
                {
                    this.mLoginToCLParams = new LoginToCLParams();
                }
                return this.mLoginToCLParams;
            }
        }
        
        public virtual IsLoggedInExpectedValues IsLoggedInExpectedValues
        {
            get
            {
                if ((this.mIsLoggedInExpectedValues == null))
                {
                    this.mIsLoggedInExpectedValues = new IsLoggedInExpectedValues();
                }
                return this.mIsLoggedInExpectedValues;
            }
        }
        
        public UIConciergeLinkWindow UIConciergeLinkWindow
        {
            get
            {
                if ((this.mUIConciergeLinkWindow == null))
                {
                    this.mUIConciergeLinkWindow = new UIConciergeLinkWindow();
                }
                return this.mUIConciergeLinkWindow;
            }
        }
        #endregion
        
        #region Fields
        private StartCLParams mStartCLParams;
        
        private LoginToCLParams mLoginToCLParams;
        
        private IsLoggedInExpectedValues mIsLoggedInExpectedValues;
        
        private UIConciergeLinkWindow mUIConciergeLinkWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'StartCL'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class StartCLParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramFiles%\BuildingLink\ConciergeLink\ConciergeLink.exe'
        /// </summary>
        public string ExePath = "C:\\Program Files (x86)\\BuildingLink\\ConciergeLink\\ConciergeLink.exe";
        
        /// <summary>
        /// Launch '%ProgramFiles%\BuildingLink\ConciergeLink\ConciergeLink.exe'
        /// </summary>
        public string AlternateExePath = "%ProgramFiles%\\BuildingLink\\ConciergeLink\\ConciergeLink.exe";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoginToCL'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class LoginToCLParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'itechdev' in first text box next to 'User Name' label
        /// </summary>
        public string UIItemEditText = "itechdev";
        
        /// <summary>
        /// Type '********' in first text box next to 'Password' label
        /// </summary>
        public string UIItemEditSendKeys = "XeDGFf2caKhnhwEdCjeB+OqZZZmZb5Ca";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'IsLoggedIn'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class IsLoggedInExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of first combo box next to 'Z' button contains 'ComboBox'
        /// </summary>
        public string UIItemComboBoxControlType = "ComboBox";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIConciergeLinkWindow : WpfWindow
    {
        
        public UIConciergeLinkWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "ConciergeLink";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ConciergeLink");
            #endregion
        }
        
        #region Properties
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        
        public UIItemCustom1 UIItemCustom1
        {
            get
            {
                if ((this.mUIItemCustom1 == null))
                {
                    this.mUIItemCustom1 = new UIItemCustom1(this);
                }
                return this.mUIItemCustom1;
            }
        }
        
        public UIItemCustom2 UIItemCustom2
        {
            get
            {
                if ((this.mUIItemCustom2 == null))
                {
                    this.mUIItemCustom2 = new UIItemCustom2(this);
                }
                return this.mUIItemCustom2;
            }
        }
        #endregion
        
        #region Fields
        private UIItemCustom mUIItemCustom;
        
        private UIItemCustom1 mUIItemCustom1;
        
        private UIItemCustom2 mUIItemCustom2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemCustom : WpfCustom
    {
        
        public UIItemCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.MainRegionView";
            this.WindowTitles.Add("ConciergeLink");
            #endregion
        }
        
        #region Properties
        public UIContentScrollViewerPane UIContentScrollViewerPane
        {
            get
            {
                if ((this.mUIContentScrollViewerPane == null))
                {
                    this.mUIContentScrollViewerPane = new UIContentScrollViewerPane(this);
                }
                return this.mUIContentScrollViewerPane;
            }
        }
        #endregion
        
        #region Fields
        private UIContentScrollViewerPane mUIContentScrollViewerPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIContentScrollViewerPane : WpfPane
    {
        
        public UIContentScrollViewerPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.ScrollViewer";
            this.SearchProperties[WpfPane.PropertyNames.AutomationId] = "ContentScrollViewer";
            this.WindowTitles.Add("ConciergeLink");
            #endregion
        }
        
        #region Properties
        public UIUserNameText UIUserNameText
        {
            get
            {
                if ((this.mUIUserNameText == null))
                {
                    this.mUIUserNameText = new UIUserNameText(this);
                }
                return this.mUIUserNameText;
            }
        }
        
        public UIPasswordText UIPasswordText
        {
            get
            {
                if ((this.mUIPasswordText == null))
                {
                    this.mUIPasswordText = new UIPasswordText(this);
                }
                return this.mUIPasswordText;
            }
        }
        
        public WpfButton UILogInButton
        {
            get
            {
                if ((this.mUILogInButton == null))
                {
                    this.mUILogInButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUILogInButton.SearchProperties[WpfButton.PropertyNames.Name] = "Log In";
                    this.mUILogInButton.WindowTitles.Add("ConciergeLink");
                    #endregion
                }
                return this.mUILogInButton;
            }
        }
        #endregion
        
        #region Fields
        private UIUserNameText mUIUserNameText;
        
        private UIPasswordText mUIPasswordText;
        
        private WpfButton mUILogInButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIUserNameText : WpfText
    {
        
        public UIUserNameText(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfText.PropertyNames.Name] = "User Name";
            this.WindowTitles.Add("ConciergeLink");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIItemEdit.WindowTitles.Add("ConciergeLink");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIPasswordText : WpfText
    {
        
        public UIPasswordText(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfText.PropertyNames.Name] = "Password";
            this.WindowTitles.Add("ConciergeLink");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIItemEdit.WindowTitles.Add("ConciergeLink");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemCustom1 : WpfCustom
    {
        
        public UIItemCustom1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.TitleBarView";
            this.WindowTitles.Add("ConciergeLink");
            #endregion
        }
        
        #region Properties
        public WpfButton UIKButton
        {
            get
            {
                if ((this.mUIKButton == null))
                {
                    this.mUIKButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIKButton.SearchProperties[WpfButton.PropertyNames.Name] = "K";
                    this.mUIKButton.WindowTitles.Add("ConciergeLink");
                    #endregion
                }
                return this.mUIKButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemCustom2 : WpfCustom
    {
        
        public UIItemCustom2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.TopLevelNavigationBarView";
            this.WindowTitles.Add("ConciergeLink");
            #endregion
        }
        
        #region Properties
        public UIZButton UIZButton
        {
            get
            {
                if ((this.mUIZButton == null))
                {
                    this.mUIZButton = new UIZButton(this);
                }
                return this.mUIZButton;
            }
        }
        #endregion
        
        #region Fields
        private UIZButton mUIZButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIZButton : WpfButton
    {
        
        public UIZButton(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfButton.PropertyNames.Name] = "Z";
            this.WindowTitles.Add("ConciergeLink");
            #endregion
        }
        
        #region Properties
        public WpfComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIItemComboBox.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIItemComboBox.WindowTitles.Add("ConciergeLink");
                    #endregion
                }
                return this.mUIItemComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WpfComboBox mUIItemComboBox;
        #endregion
    }
}
